# -*- coding: utf-8 -*-
"""GT-social.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOG5-33i7Pcvq4HgaPbMLY6X0UAZfUPf

# Data Exploration
"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd

df = pd.read_csv("mental_health_social_media_dataset.csv")

df

print(df.shape)

print(df.info())

print(df.isnull().sum())

df.describe()

"""# Data Preprocessing"""

df = df.drop(["person_name","date"], axis=1)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])
df["platform"] = le.fit_transform(df["platform"])
df["mental_state"] = le.fit_transform(df["mental_state"])

"""# EDA"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("whitegrid")
sns.set_palette("Set2")
plt.figure(figsize=(8,5))

plt.figure(figsize=(8,5))
sns.countplot(x="mental_state", data=df, palette="viridis")

plt.title("Distribution of Mental Health States", fontsize=14, fontweight="bold")
plt.xlabel("Mental State")
plt.ylabel("Number of Users")

plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    x="daily_screen_time_min",
    y="stress_level",
    hue="mental_state",
    palette="coolwarm",
    data=df
)

plt.title("Screen Time vs Stress Level")
plt.xlabel("Daily Screen Time (minutes)")
plt.ylabel("Stress Level")

plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x="platform", data=df, palette="Set3")

plt.title("Social Media Platform Usage")
plt.xlabel("Platform")
plt.ylabel("Number of Users")

plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(
    x="mental_state",
    y="sleep_hours",
    palette="pastel",
    data=df
)

plt.title("Sleep Hours vs Mental Health State")
plt.xlabel("Mental State")
plt.ylabel("Sleep Hours")

plt.show()

"""# Feature Selection"""

X = df.drop("mental_state", axis=1)
y = df["mental_state"]

"""# Train-Test Split"""

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

"""# Model Training"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train,y_train)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train,y_train)

from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train,y_train)

"""# Model Evaluation"""

from sklearn.metrics import f1_score,classification_report, accuracy_score, confusion_matrix

pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test,pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred))
print("\nClassification Report:\n", classification_report(y_test, pred))

pred1 = dt.predict(X_test)

print("Accuracy:", accuracy_score(y_test,pred1))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred1))
print("\nClassification Report:\n", classification_report(y_test, pred1))

pred2 = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test,pred2))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred2))
print("\nClassification Report:\n", classification_report(y_test, pred2))

"""# Save Model (Pickle)"""

import pickle

pickle.dump(rf, open("mental_health_model.pkl","wb"))